" PLUGIN SECTION, MESS {{{
" Vundle vimrc
set nocompatible              " be iMproved, required
filetype off                  " required

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
" alternatively, pass a path where Vundle should install plugins
" call vundle#begin('~/some/path/here')
"
let g:ycm_confirm_extra_conf = 0 
"
" let Vundle manage Vundle, required
Plugin 'VundleVim/Vundle.vim'

Plugin 'Valloric/YouCompleteMe'
Plugin 'The-NERD-tree'
Plugin 'junegunn/goyo.vim'
" Plugin 'Lokaltog/powerline'
Plugin 'itchyny/lightline.vim'
Bundle 'https://github.com/sagarrakshe/toggle-bool'
set laststatus=2
let g:lightline = {
      \ 'colorscheme': 'solarized',
      \ }

"
" End configuration, makes the plugins available
call vundle#end()
filetype plugin indent on

map <C-]> :YcmCompleter GoToImprecise<CR>
map <C-n> :NERDTreeToggle<CR>
" autocmd vimenter *  NERDTree
" }}}
" LEADER SHORTCUTS {{{
let mapleader=","       "Coma is the leader!
" }}}
" SPACES, TABS, COLOURS {{{
syntax enable           "Syntax processing
set tabstop=2           "Spaces per tab
set shiftwidth=2        "Spaces
set softtabstop=2       "Spaces in tab when editing
set expandtab           "Tabs ARE spaces
syntax on
colorscheme solarized 
call togglebg#map("<F5>")
"colorscheme phd
" }}}
" UI CONFIG {{{
set number	" shows number lines
set relativenumber      "Shows relative number. Map below
set cursorline	" highlights line
set showcmd " shows last command used at the bottom
filetype indent on      "Load filetype-specific indent files eg. .vim/indent/python.vim
set wildmenu            "visual autocomplete for command menu
set lazyredraw          "Redraw only when we need to.
set showmatch           "Highlight matching [{()}]
set autoindent
set smartindent
" }}}
"SEARCHING {{{
set incsearch           "Search as characters are entered
set hlsearch            "Highlight matches
set ignorecase          "Case insensitivity
set smartcase           "Overrides ignorecase if pattern contains upcase

" Keep search results at the center of screen
nnoremap n nzz
nnoremap N Nzz
nnoremap * *zz
nnoremap # #zz
nnoremap g* g*zz
nnoremap g# g#zz

" Remove escape and use jk instead. 
inoremap jk <esc>
inoremap <esc> <nop>

" Run leader and space instead :noh 
nnoremap <silent> <leader><cr> :noh<CR>


" }}}
" FOLDING {{{
set foldenable          " enable folding
set foldlevelstart=10   " open most folds by defaulti
set foldnestmax=10      " 10 nested fold max
set foldlevel=0
" space open/closes folds
nnoremap <space> za
set foldmethod=indent   " fold based on indent leveli
" }}}
" HIGHLIGHTS LAST INSERTED TEXT {{{
nnoremap gV `[v`]
" }}}
" allows cursor change in tmux mode {{{
if exists('$TMUX')
  let &t_SI = "\<Esc>Ptmux;\<Esc>\<Esc>]50;CursorShape=1\x7\<Esc>\\"
  let &t_EI = "\<Esc>Ptmux;\<Esc>\<Esc>]50;CursorShape=0\x7\<Esc>\\"
else
  let &t_SI = "\<Esc>]50;CursorShape=1\x7"
  let &t_EI = "\<Esc>]50;CursorShape=0\x7"
endif
" }}}

" MAPPING {{{
" Remove arrows, it's better that way.
nnoremap <Left>   :echoe "Use h"<CR>
nnoremap <Right>  :echoe "Use l"<CR>
nnoremap <Up>     :echoe "Use k"<CR>
nnoremap <Down>   :echoe "Use j"<CR>

" Toggle between relative number & absolute number mode
nnoremap <silent> <leader>nb :set relativenumber!<CR>

" Make j and k move to the next row, not file line
nnoremap j gj
nnoremap k gk

" Move to beginning/end of line
nnoremap B ^
nnoremap E $

" Select all text
nnoremap vA ggVA

" Quick Save
nnoremap <S-s> :w<CR>

" Yank to end of line
nnoremap Y y$

" Delete to the end of line
nnoremap D d$

" Switch between tabs
nnoremap <leader>1 1gt
nnoremap <leader>2 2gt
nnoremap <leader>3 3gt
nnoremap <leader>4 4gt
nnoremap <leader>5 5gt
nnoremap <leader>6 6gt
nnoremap <leader>7 7gt
nnoremap <leader>8 8gt
nnoremap <leader>9 9gt

" Easiely reate a new tab
nnoremap <leader>tN :tabnew<CR>

" Easiely close a tab
nnoremap <leader>tc :tabclose<CR>

" Easiely move a tab
nnoremap <leader>tm :tabmove<CR>

" Easiely go to next tab
nnoremap <leader>tn :tabnext<CR>

" Easiely go to previous tab
nnoremap <leader>tp :tabprevious<CR>
" }}}

noremap <leader>r :ToggleBool<CR>
set runtimepath += "~/.vim/ibus.vim"
set modeline
set modelines=1
" vim:set foldmethod=marker foldlevel=0:
